CREATE TABLE brand (
	brand_id INTEGER NOT NULL,
	brand_name CHARACTER VARYING(100) NOT NULL,
	CONSTRAINT PK_BRAND_ID PRIMARY KEY (brand_id)
);

ALTER TABLE brand OWNER TO postgres;

CREATE TABLE cartype (
	cartype_id INTEGER NOT NULL,
	car_brand_id INTEGER NOT NULL,
	type_of_car CHARACTER VARYING(100) NOT NULL,
	model CHARACTER VARYING(100) NOT NULL,
	CONSTRAINT PK_CARTYPE_ID PRIMARY KEY (cartype_id),
	CONSTRAINT FK_CARBRAND_BRAND FOREIGN KEY (car_brand_id)
	  REFERENCES brand (brand_id) MATCH SIMPLE ON UPDATE RESTRICT ON DELETE RESTRICT
);

ALTER TABLE cartype OWNER TO postgres;

CREATE TABLE car (
	car_id INTEGER NOT NULL,
	car_cartype_id INTEGER NOT NULL,
	production_date DATE NOT NULL,
	fuel CHARACTER VARYING(100) NOT NULL,
	color CHARACTER VARYING(100) NOT NULL,
	price REAL NOT NULL,
	CONSTRAINT PK_CAR_ID PRIMARY KEY (car_id),
	CONSTRAINT FK_CAR_CARTYPE FOREIGN KEY (car_cartype_id)
	  REFERENCES cartype (cartype_id) MATCH SIMPLE ON UPDATE RESTRICT ON DELETE RESTRICT
);

ALTER TABLE car OWNER TO postgres;

CREATE TABLE customer (
	customer_id INTEGER NOT NULL,
	registration_date DATE NOT NULL,
	name CHARACTER VARYING(100) NOT NULL,
	login_name CHARACTER VARYING(100) NOT NULL,
	email CHARACTER VARYING(100) NOT NULL,
	passwd CHARACTER VARYING(100) NOT NULL,
	CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY (customer_id),
);

ALTER TABLE customer OWNER TO postgres;

CREATE TABLE rent (
	rent_id INTEGER NOT NULL,
	rent_car_id INTEGER NOT NULL,
	rent_customer_id INTEGER NOT NULL,
	rent_date DATE NOT NULL,
	CONSTRAINT PK_CUSTOMER_ID PRIMARY KEY (rent_id),
	CONSTRAINT FK_RENT_CAR FOREIGN KEY (rent_car_id)
	  REFERENCES car (car_id) MATCH SIMPLE ON UPDATE RESTRICT ON DELETE RESTRICT
	CONSTRAINT FK_RENT_CUSTOMER FOREIGN KEY (rent_customer_id)
	  REFERENCES customer (customer_id) MATCH SIMPLE ON UPDATE RESTRICT ON DELETE RESTRICT
);

ALTER TABLE rent OWNER TO postgres;