CREATE TABLE User(
	userID SERIAL NOT NULL,
	FirstName CHARACTER VARYING(100) NOT NULL,
	LastName CHARACTER VARYING(100) NOT NULL,
	BirthDate DATE NOT NULL,
	Height INTEGER NOT NULL,
	Weight INTEGER(10) NOT NULL,
	Sex BOOLEAN NOT NULL,
	CONSTRAINT PK_USERS_ID PRIMARY KEY (userID)
);

ALTER TABLE User OWNER TO postgres;

CREATE TABLE Sleep(
);
ALTER TABLE Sleep OWNER TO postgres;

CREATE TABLE Rating(
	RatingID SERIAL NOT NULL,
	Relaxed  INTEGER NOT NULL,
	Feel INTEGER NOT NULL
	CONSTRAINT FK_FEEL FOREIGN KEY (Feel)
		  REFERENCES Feel (FeelID) MATCH SIMPLE ON UPDATE RESTRICT ON DELETE RESTRICT
);
ALTER TABLE Rating OWNER TO postgres;

CREATE TABLE Eat(
);
ALTER TABLE Eat OWNER TO postgres;

CREATE TABLE Sports(
);
ALTER TABLE Sports OWNER TO postgres;

CREATE TABLE RatingString(
);
ALTER TABLE RatingString OWNER TO postgres;

CONSTRAINT FK_CARBRAND_BRAND FOREIGN KEY (car_brand_id)
      REFERENCES brand (brand_id) MATCH SIMPLE ON UPDATE RESTRICT ON DELETE RESTRICT